
// 
//	This code was generated by a tool. Any changes made manually will be lost
//	the next time this code is regenerated.
// 
//	(c) 2014 SharpFu
//
 
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;
 
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("SharpFu")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: NeutralResourcesLanguageAttribute("en")]
 
[assembly: AssemblyProduct("SharpFu Application Framework")]
[assembly: AssemblyCopyright("(c) 2014 SharpFu")]
[assembly: AssemblyTrademark("@sharpfu")]

[assembly: AssemblyVersion("1.0.7.23593")]
[assembly: AssemblyFileVersion("1.0.7.23593")]
 
